# Generated by Django 4.0.2 on 2022-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='catagory_img',
            field=models.ImageField(upload_to='shop/images/catagory/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_img',
            field=models.ImageField(upload_to='shop/images/Product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
